/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.augustotwelve;

import com.mycompany.augustotwelve.screens.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author dam_eml
 */
public class Menu extends javax.swing.JFrame {

    private final Color GO = new Color(85,65,129);
    private final Color GB = new Color(95,75,139);
    private final Color LO = new Color(126,99,184);
    private final Color LB = new Color(136,119,194);
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        icon.setIcon(new ImageIcon("src/Logo100.png"));
        Menu.setDefaultLookAndFeelDecorated(true);
        JFrame m = this;
        m.setIconImage(new ImageIcon("src/Logo100.png").getImage());
        this.setSize(800,545);
        
        
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pr = new javax.swing.JPanel();
        l = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        mesa = new javax.swing.JPanel();
        Mesa = new javax.swing.JButton();
        mo = new javax.swing.JPanel();
        ma = new javax.swing.JPanel();
        malta = new javax.swing.JButton();
        mb = new javax.swing.JPanel();
        mbaja = new javax.swing.JButton();
        mm = new javax.swing.JPanel();
        mmodi = new javax.swing.JButton();
        mv = new javax.swing.JPanel();
        mvisu = new javax.swing.JButton();
        prod = new javax.swing.JPanel();
        Prod = new javax.swing.JButton();
        po = new javax.swing.JPanel();
        pa = new javax.swing.JPanel();
        palta = new javax.swing.JButton();
        pb = new javax.swing.JPanel();
        pbaja = new javax.swing.JButton();
        pm = new javax.swing.JPanel();
        pmodi = new javax.swing.JButton();
        pv = new javax.swing.JPanel();
        pvisu = new javax.swing.JButton();
        formularios = new javax.swing.JPanel();

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUGUST TWELVE");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(750, 500));

        pr.setBackground(new java.awt.Color(95, 75, 139));
        pr.setPreferredSize(new java.awt.Dimension(150, 750));

        l.setBackground(new java.awt.Color(95, 75, 139));
        l.setPreferredSize(new java.awt.Dimension(150, 100));

        javax.swing.GroupLayout lLayout = new javax.swing.GroupLayout(l);
        l.setLayout(lLayout);
        lLayout.setHorizontalGroup(
            lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icon)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        lLayout.setVerticalGroup(
            lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lLayout.createSequentialGroup()
                .addComponent(icon)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        mesa.setBackground(new java.awt.Color(95, 75, 139));
        mesa.setPreferredSize(new java.awt.Dimension(150, 200));

        Mesa.setForeground(new java.awt.Color(255, 255, 255));
        Mesa.setText("Mesa");
        Mesa.setBorderPainted(false);
        Mesa.setContentAreaFilled(false);
        Mesa.setMaximumSize(new java.awt.Dimension(150, 40));
        Mesa.setMinimumSize(new java.awt.Dimension(150, 40));
        Mesa.setPreferredSize(new java.awt.Dimension(150, 40));
        Mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MesaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MesaMouseExited(evt);
            }
        });
        Mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesaActionPerformed(evt);
            }
        });

        mo.setPreferredSize(new java.awt.Dimension(150, 160));

        ma.setBackground(new java.awt.Color(136, 119, 194));
        ma.setPreferredSize(new java.awt.Dimension(150, 40));

        malta.setForeground(new java.awt.Color(255, 255, 255));
        malta.setMnemonic('A');
        malta.setText("Alta");
        malta.setToolTipText("Crear una nueva mesa");
        malta.setBorderPainted(false);
        malta.setContentAreaFilled(false);
        malta.setMaximumSize(new java.awt.Dimension(150, 40));
        malta.setMinimumSize(new java.awt.Dimension(150, 40));
        malta.setPreferredSize(new java.awt.Dimension(150, 40));
        malta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maltaMouseExited(evt);
            }
        });
        malta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maLayout = new javax.swing.GroupLayout(ma);
        ma.setLayout(maLayout);
        maLayout.setHorizontalGroup(
            maLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(maLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(malta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        maLayout.setVerticalGroup(
            maLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(maLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(malta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mb.setBackground(new java.awt.Color(136, 119, 194));
        mb.setPreferredSize(new java.awt.Dimension(150, 40));

        mbaja.setForeground(new java.awt.Color(255, 255, 255));
        mbaja.setMnemonic('B');
        mbaja.setText("Baja");
        mbaja.setToolTipText("Eliminar una mesa");
        mbaja.setBorderPainted(false);
        mbaja.setContentAreaFilled(false);
        mbaja.setMaximumSize(new java.awt.Dimension(150, 40));
        mbaja.setMinimumSize(new java.awt.Dimension(150, 40));
        mbaja.setPreferredSize(new java.awt.Dimension(150, 40));
        mbaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mbajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mbajaMouseExited(evt);
            }
        });
        mbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mbLayout = new javax.swing.GroupLayout(mb);
        mb.setLayout(mbLayout);
        mbLayout.setHorizontalGroup(
            mbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(mbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mbLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mbaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        mbLayout.setVerticalGroup(
            mbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mbLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mbaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mm.setBackground(new java.awt.Color(136, 119, 194));
        mm.setPreferredSize(new java.awt.Dimension(150, 40));

        mmodi.setForeground(new java.awt.Color(255, 255, 255));
        mmodi.setMnemonic('M');
        mmodi.setText("Modificar");
        mmodi.setToolTipText("Editar una mesa");
        mmodi.setBorderPainted(false);
        mmodi.setContentAreaFilled(false);
        mmodi.setMaximumSize(new java.awt.Dimension(150, 40));
        mmodi.setMinimumSize(new java.awt.Dimension(150, 40));
        mmodi.setPreferredSize(new java.awt.Dimension(150, 40));
        mmodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmodiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mmodiMouseExited(evt);
            }
        });
        mmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmodiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mmLayout = new javax.swing.GroupLayout(mm);
        mm.setLayout(mmLayout);
        mmLayout.setHorizontalGroup(
            mmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(mmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mmLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mmodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        mmLayout.setVerticalGroup(
            mmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mmLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mmodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mv.setBackground(new java.awt.Color(136, 119, 194));
        mv.setPreferredSize(new java.awt.Dimension(150, 40));

        mvisu.setForeground(new java.awt.Color(255, 255, 255));
        mvisu.setMnemonic('V');
        mvisu.setText("Visualizar");
        mvisu.setToolTipText("Ver lista de mesas");
        mvisu.setBorderPainted(false);
        mvisu.setContentAreaFilled(false);
        mvisu.setMaximumSize(new java.awt.Dimension(150, 40));
        mvisu.setMinimumSize(new java.awt.Dimension(150, 40));
        mvisu.setPreferredSize(new java.awt.Dimension(150, 40));
        mvisu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mvisuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mvisuMouseExited(evt);
            }
        });
        mvisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvisuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mvLayout = new javax.swing.GroupLayout(mv);
        mv.setLayout(mvLayout);
        mvLayout.setHorizontalGroup(
            mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mvLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mvisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        mvLayout.setVerticalGroup(
            mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mvLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mvisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout moLayout = new javax.swing.GroupLayout(mo);
        mo.setLayout(moLayout);
        moLayout.setHorizontalGroup(
            moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moLayout.createSequentialGroup()
                .addComponent(mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        moLayout.setVerticalGroup(
            moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
            .addGroup(moLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(moLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mesaLayout = new javax.swing.GroupLayout(mesa);
        mesa.setLayout(mesaLayout);
        mesaLayout.setHorizontalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mesaLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        mesaLayout.setVerticalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mesaLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mesaLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );

        prod.setBackground(new java.awt.Color(95, 75, 139));
        prod.setPreferredSize(new java.awt.Dimension(150, 200));

        Prod.setForeground(new java.awt.Color(255, 255, 255));
        Prod.setText("Producto");
        Prod.setBorderPainted(false);
        Prod.setContentAreaFilled(false);
        Prod.setMaximumSize(new java.awt.Dimension(150, 40));
        Prod.setMinimumSize(new java.awt.Dimension(150, 40));
        Prod.setPreferredSize(new java.awt.Dimension(150, 40));
        Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProdMouseExited(evt);
            }
        });
        Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdActionPerformed(evt);
            }
        });

        po.setPreferredSize(new java.awt.Dimension(150, 160));

        pa.setBackground(new java.awt.Color(136, 119, 194));
        pa.setPreferredSize(new java.awt.Dimension(150, 40));

        palta.setForeground(new java.awt.Color(255, 255, 255));
        palta.setMnemonic('A');
        palta.setText("Alta");
        palta.setToolTipText("Crear un producto");
        palta.setBorderPainted(false);
        palta.setContentAreaFilled(false);
        palta.setMaximumSize(new java.awt.Dimension(150, 40));
        palta.setMinimumSize(new java.awt.Dimension(150, 40));
        palta.setPreferredSize(new java.awt.Dimension(150, 40));
        palta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paltaMouseExited(evt);
            }
        });
        palta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paLayout = new javax.swing.GroupLayout(pa);
        pa.setLayout(paLayout);
        paLayout.setHorizontalGroup(
            paLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(paLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(palta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        paLayout.setVerticalGroup(
            paLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(paLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(palta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pb.setBackground(new java.awt.Color(136, 119, 194));
        pb.setPreferredSize(new java.awt.Dimension(150, 40));

        pbaja.setForeground(new java.awt.Color(255, 255, 255));
        pbaja.setMnemonic('B');
        pbaja.setText("Baja");
        pbaja.setToolTipText("Eliminar un producto");
        pbaja.setBorderPainted(false);
        pbaja.setContentAreaFilled(false);
        pbaja.setMaximumSize(new java.awt.Dimension(150, 40));
        pbaja.setMinimumSize(new java.awt.Dimension(150, 40));
        pbaja.setPreferredSize(new java.awt.Dimension(150, 40));
        pbaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbajaMouseExited(evt);
            }
        });
        pbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbLayout = new javax.swing.GroupLayout(pb);
        pb.setLayout(pbLayout);
        pbLayout.setHorizontalGroup(
            pbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(pbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pbLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pbaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        pbLayout.setVerticalGroup(
            pbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pbLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pbaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pm.setBackground(new java.awt.Color(136, 119, 194));
        pm.setPreferredSize(new java.awt.Dimension(150, 40));

        pmodi.setForeground(new java.awt.Color(255, 255, 255));
        pmodi.setMnemonic('M');
        pmodi.setText("Modificar");
        pmodi.setToolTipText("Editar un producto");
        pmodi.setBorderPainted(false);
        pmodi.setContentAreaFilled(false);
        pmodi.setMaximumSize(new java.awt.Dimension(150, 40));
        pmodi.setMinimumSize(new java.awt.Dimension(150, 40));
        pmodi.setPreferredSize(new java.awt.Dimension(150, 40));
        pmodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmodiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmodiMouseExited(evt);
            }
        });
        pmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmodiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pmLayout = new javax.swing.GroupLayout(pm);
        pm.setLayout(pmLayout);
        pmLayout.setHorizontalGroup(
            pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pmLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pmodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        pmLayout.setVerticalGroup(
            pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pmLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pmodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pv.setBackground(new java.awt.Color(136, 119, 194));
        pv.setPreferredSize(new java.awt.Dimension(150, 40));

        pvisu.setForeground(new java.awt.Color(255, 255, 255));
        pvisu.setMnemonic('V');
        pvisu.setText("Visualizar");
        pvisu.setToolTipText("Ver lista de productos");
        pvisu.setBorderPainted(false);
        pvisu.setContentAreaFilled(false);
        pvisu.setMaximumSize(new java.awt.Dimension(150, 40));
        pvisu.setMinimumSize(new java.awt.Dimension(150, 40));
        pvisu.setPreferredSize(new java.awt.Dimension(150, 40));
        pvisu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvisuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvisuMouseExited(evt);
            }
        });
        pvisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvisuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pvLayout = new javax.swing.GroupLayout(pv);
        pv.setLayout(pvLayout);
        pvLayout.setHorizontalGroup(
            pvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(pvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pvLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pvisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        pvLayout.setVerticalGroup(
            pvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pvLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pvisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout poLayout = new javax.swing.GroupLayout(po);
        po.setLayout(poLayout);
        poLayout.setHorizontalGroup(
            poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poLayout.createSequentialGroup()
                .addComponent(pv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        poLayout.setVerticalGroup(
            poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(pv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
            .addGroup(poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(poLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout prodLayout = new javax.swing.GroupLayout(prod);
        prod.setLayout(prodLayout);
        prodLayout.setHorizontalGroup(
            prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prodLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        prodLayout.setVerticalGroup(
            prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prodLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout prLayout = new javax.swing.GroupLayout(pr);
        pr.setLayout(prLayout);
        prLayout.setHorizontalGroup(
            prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        prLayout.setVerticalGroup(
            prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prLayout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout formulariosLayout = new javax.swing.GroupLayout(formularios);
        formularios.setLayout(formulariosLayout);
        formulariosLayout.setHorizontalGroup(
            formulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        formulariosLayout.setVerticalGroup(
            formulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formularios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pr, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(formularios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MesaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MesaMouseEntered
        mesa.setBackground(GO);
    }//GEN-LAST:event_MesaMouseEntered

    private void ProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdMouseEntered
        prod.setBackground(GO);
    }//GEN-LAST:event_ProdMouseEntered

    private void MesaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MesaMouseExited
         mesa.setBackground((!Mesa.isEnabled())?GO:GB);
    }//GEN-LAST:event_MesaMouseExited

    private void ProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdMouseExited
        prod.setBackground((!Prod.isEnabled())?GO:GB);
    }//GEN-LAST:event_ProdMouseExited

    private void maltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maltaMouseEntered
        ma.setBackground(LO);
    }//GEN-LAST:event_maltaMouseEntered

    private void mbajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbajaMouseEntered
        mb.setBackground(LO);
    }//GEN-LAST:event_mbajaMouseEntered

    private void mmodiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmodiMouseEntered
        mm.setBackground(LO);
    }//GEN-LAST:event_mmodiMouseEntered

    private void mvisuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mvisuMouseEntered
        mv.setBackground(LO);
    }//GEN-LAST:event_mvisuMouseEntered

    private void paltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paltaMouseEntered
        pa.setBackground(LO);
    }//GEN-LAST:event_paltaMouseEntered

    private void pbajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbajaMouseEntered
        pb.setBackground(LO);
    }//GEN-LAST:event_pbajaMouseEntered

    private void pmodiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodiMouseEntered
        pm.setBackground(LO);
    }//GEN-LAST:event_pmodiMouseEntered

    private void pvisuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvisuMouseEntered
        pv.setBackground(LO);
    }//GEN-LAST:event_pvisuMouseEntered

    private void maltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maltaMouseExited
       ma.setBackground((!malta.isEnabled())?LO:LB);
    }//GEN-LAST:event_maltaMouseExited

    private void mbajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbajaMouseExited
        mb.setBackground((!mbaja.isEnabled())?LO:LB);
    }//GEN-LAST:event_mbajaMouseExited

    private void mmodiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmodiMouseExited
        mm.setBackground((!mmodi.isEnabled())?LO:LB);
    }//GEN-LAST:event_mmodiMouseExited

    private void mvisuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mvisuMouseExited
        mv.setBackground((!mvisu.isEnabled())?LO:LB);
    }//GEN-LAST:event_mvisuMouseExited

    private void paltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paltaMouseExited
        pa.setBackground((!palta.isEnabled())?LO:LB);
    }//GEN-LAST:event_paltaMouseExited

    private void pbajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbajaMouseExited
        pb.setBackground((!pbaja.isEnabled())?LO:LB);
    }//GEN-LAST:event_pbajaMouseExited

    private void pmodiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodiMouseExited
        pm.setBackground((!pmodi.isEnabled())?LO:LB);
    }//GEN-LAST:event_pmodiMouseExited

    private void pvisuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvisuMouseExited
        pv.setBackground((!pvisu.isEnabled())?LO:LB);
    }//GEN-LAST:event_pvisuMouseExited

    private void MesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesaActionPerformed
        mesa.setBackground(GO);
        Prod.setEnabled(true);
        Mesa.setEnabled(false);
        prod.setBackground(GB);
        mesa.setSize(150,200);
        prod.setSize(150,40);
        prod.setLocation(0,300);
    }//GEN-LAST:event_MesaActionPerformed

    private void ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdActionPerformed
        prod.setBackground(GO);
        Prod.setEnabled(false);
        Mesa.setEnabled(true);
        mesa.setBackground(GB);
        prod.setSize(150,200);
        mesa.setSize(150,40);
        prod.setLocation(0,140);
    }//GEN-LAST:event_ProdActionPerformed

    private void maltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltaActionPerformed
        reset();
        esteBoton(ma,malta);
        AddMesa mesaalta = new AddMesa();
        formularios.add(mesaalta);
        mesaalta.setSize(600,500);
        mesaalta.setVisible(true);
        formularios.revalidate();
        formularios.repaint();  
        
    }//GEN-LAST:event_maltaActionPerformed

    private void mbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbajaActionPerformed
       reset();
       esteBoton(mb,mbaja);     
       EliminaMesa mesabaja = new EliminaMesa();
       formularios.add(mesabaja);
       mesabaja.setSize(600,500);
       mesabaja.setVisible(true);
       formularios.revalidate();
       formularios.repaint();  
    }//GEN-LAST:event_mbajaActionPerformed

    private void mmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmodiActionPerformed
       reset();
       esteBoton(mm,mmodi);
       modMesa mesamodi = new modMesa();
       formularios.add(mesamodi);
       mesamodi.setSize(600,500);
       mesamodi.setVisible(true);
       formularios.revalidate();
       formularios.repaint();  
    }//GEN-LAST:event_mmodiActionPerformed

    private void mvisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvisuActionPerformed
       reset();
       esteBoton(mv,mvisu);
        //INSERTAR VENTANA UWU
       verMesa mesavisu= new verMesa();
       formularios.add(mesavisu);
       mesavisu.setSize(600,500);
       mesavisu.setVisible(true);
       formularios.revalidate();
       formularios.repaint();       
    }//GEN-LAST:event_mvisuActionPerformed

    private void paltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paltaActionPerformed
       reset();
       esteBoton(pa,palta);
        //INSERTAR VENTANA UWU
       AnyadirProducto anyadirProducto = new AnyadirProducto();
       formularios.add(anyadirProducto);
       anyadirProducto.setSize(600,500);
       anyadirProducto.setVisible(true);
       formularios.revalidate();
       formularios.repaint();
    }//GEN-LAST:event_paltaActionPerformed

    private void pbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbajaActionPerformed
        reset();
        esteBoton(pb,pbaja);
        EliminarProducto eliminarProducto = new EliminarProducto();
        formularios.add(eliminarProducto);
        eliminarProducto.setSize(600,500);
        eliminarProducto.setVisible(true);
        formularios.revalidate();
        formularios.repaint();
    }//GEN-LAST:event_pbajaActionPerformed

    private void pmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmodiActionPerformed
       reset();
       esteBoton(pm,pmodi);
       ModificarProducto modificarProducto = new ModificarProducto();
       formularios.add(modificarProducto);
       modificarProducto.setSize(600,500);
       modificarProducto.setVisible(true);
       formularios.revalidate();
       formularios.repaint();  
    }//GEN-LAST:event_pmodiActionPerformed

    private void pvisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvisuActionPerformed
        reset();
        esteBoton(pv,pvisu);
        VerProducto verProducto = new VerProducto();
        formularios.add(verProducto);
        verProducto.setSize(600,500);
        verProducto.setVisible(true);
        formularios.revalidate();
        formularios.repaint();  
       
    }//GEN-LAST:event_pvisuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mesa;
    private javax.swing.JButton Prod;
    private javax.swing.JPanel formularios;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel l;
    private javax.swing.JPanel ma;
    private javax.swing.JButton malta;
    private javax.swing.JPanel mb;
    private javax.swing.JButton mbaja;
    private javax.swing.JPanel mesa;
    private javax.swing.JPanel mm;
    private javax.swing.JButton mmodi;
    private javax.swing.JPanel mo;
    private javax.swing.JPanel mv;
    private javax.swing.JButton mvisu;
    private javax.swing.JPanel pa;
    private javax.swing.JButton palta;
    private javax.swing.JPanel pb;
    private javax.swing.JButton pbaja;
    private javax.swing.JPanel pm;
    private javax.swing.JButton pmodi;
    private javax.swing.JPanel po;
    private javax.swing.JPanel pr;
    private javax.swing.JPanel prod;
    private javax.swing.JPanel pv;
    private javax.swing.JButton pvisu;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        
        formularios.removeAll();
        
        malta.setEnabled(true);
        mbaja.setEnabled(true);
        mmodi.setEnabled(true);
        mvisu.setEnabled(true);
        
        palta.setEnabled(true);
        pbaja.setEnabled(true);
        pmodi.setEnabled(true);
        pvisu.setEnabled(true);
        
        ma.setBackground(LB);
        mb.setBackground(LB);
        mm.setBackground(LB);
        mv.setBackground(LB);
        
        pa.setBackground(LB);
        pb.setBackground(LB);
        pm.setBackground(LB);
        pv.setBackground(LB);
    
    }
    
    private void esteBoton(JPanel p, JButton b){
        
        p.setBackground(LO);
        b.setEnabled(false);
        
    }
}
