/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.augustotwelve.screens;

import clients.ProductoClient;
import javax.swing.table.DefaultTableModel;
import models.Producto;

/**
 *
 * @author dam_mml
 */
public class ModificarProducto extends javax.swing.JPanel {

    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto() {
        initComponents();
        actualizaTabla();
    }
private void actualizaTabla(){
        String[] datos  = new String[5];
        String[] titulos = new String[] {"Id","Nombre","Tipo","Precio","Stock"};
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        ProductoClient pc = new ProductoClient();
        for(Producto m : pc.getProductos()){
        datos[0]=String.valueOf(m.getId());
        datos[1]=String.valueOf(m.getNombre());
        datos[2]=String.valueOf(m.getTipo());
        datos[3]=String.valueOf(m.getPrecio());
        datos[4]=String.valueOf(m.getStock());
        
        modelo.addRow(datos);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ModificarProductoCerrarButton = new javax.swing.JButton();
        ModificarProductoModificarButton = new javax.swing.JButton();
        ModificarProductoScrollPanelTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ModificarProductoScrollPanelDescripcion = new javax.swing.JScrollPane();
        ModificarProductoDescripcion = new javax.swing.JTextArea();
        ModificarProductoScrollPanelImagen = new javax.swing.JScrollPane();
        ModificarProductoImagen = new javax.swing.JTextArea();
        ModificarProductoTipo = new javax.swing.JTextField();
        ModificarProductoNombre = new javax.swing.JTextField();
        ModificarProductoStock = new javax.swing.JSpinner();
        ModificarProductoPrecio = new javax.swing.JSpinner();
        ModificarProductoNombreLabel = new javax.swing.JLabel();
        ModificarProductoDescripcionLabel = new javax.swing.JLabel();
        ModificarProductoPrecioLabel = new javax.swing.JLabel();
        ModificarProductoStockLabel = new javax.swing.JLabel();
        ModificarProductoTipoLabel = new javax.swing.JLabel();
        ModificarProductoImagenLabel = new javax.swing.JLabel();

        jLabel3.setText("Descripción");

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        ModificarProductoCerrarButton.setText("Cerrar");
        ModificarProductoCerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoCerrarButtonActionPerformed(evt);
            }
        });

        ModificarProductoModificarButton.setText("Modificar");
        ModificarProductoModificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoModificarButtonActionPerformed(evt);
            }
        });

        ModificarProductoScrollPanelTable.setPreferredSize(new java.awt.Dimension(580, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(580, 200));
        jTable1.setRequestFocusEnabled(false);
        ModificarProductoScrollPanelTable.setViewportView(jTable1);

        ModificarProductoDescripcion.setColumns(20);
        ModificarProductoDescripcion.setRows(5);
        ModificarProductoScrollPanelDescripcion.setViewportView(ModificarProductoDescripcion);

        ModificarProductoImagen.setColumns(20);
        ModificarProductoImagen.setRows(5);
        ModificarProductoScrollPanelImagen.setViewportView(ModificarProductoImagen);

        ModificarProductoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoTipoActionPerformed(evt);
            }
        });

        ModificarProductoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoNombreActionPerformed(evt);
            }
        });

        ModificarProductoStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ModificarProductoPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        ModificarProductoNombreLabel.setText("Nombre");

        ModificarProductoDescripcionLabel.setText("Descripción");

        ModificarProductoPrecioLabel.setText("Precio");

        ModificarProductoStockLabel.setText("Stock");

        ModificarProductoTipoLabel.setText("Tipo");

        ModificarProductoImagenLabel.setText("Imagen (URL)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModificarProductoNombreLabel)
                    .addComponent(ModificarProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ModificarProductoScrollPanelDescripcion)
                        .addComponent(ModificarProductoDescripcionLabel))
                    .addComponent(ModificarProductoPrecioLabel)
                    .addComponent(ModificarProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModificarProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarProductoStockLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ModificarProductoTipoLabel)
                        .addComponent(ModificarProductoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModificarProductoScrollPanelImagen)
                        .addComponent(ModificarProductoImagenLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ModificarProductoModificarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModificarProductoCerrarButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ModificarProductoScrollPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarProductoNombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarProductoDescripcionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoScrollPanelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarProductoTipoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarProductoImagenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoScrollPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarProductoStockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarProductoPrecioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificarProductoModificarButton)
                    .addComponent(ModificarProductoCerrarButton))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ModificarProductoScrollPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarProductoCerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoCerrarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ModificarProductoCerrarButtonActionPerformed

    private void ModificarProductoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoNombreActionPerformed
        Producto p = new Producto(
        ModificarProductoNombre.getText(),
                ModificarProductoDescripcion.getText(),
                ModificarProductoPrecio.getComponentCount(),
                ModificarProductoStock.getComponentCount(),
                ModificarProductoTipo.getText(),
                ModificarProductoImagen.getText()
                
        );
        
        ProductoClient pc = new ProductoClient();
        
        pc.modificaProducto(Long.parseLong((String)jTable1.getValueAt(jTable1.getSelectedRow(),0)),p);
    }//GEN-LAST:event_ModificarProductoNombreActionPerformed

    private void ModificarProductoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarProductoTipoActionPerformed

    private void ModificarProductoModificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoModificarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarProductoModificarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarProductoCerrarButton;
    private javax.swing.JTextArea ModificarProductoDescripcion;
    private javax.swing.JLabel ModificarProductoDescripcionLabel;
    private javax.swing.JTextArea ModificarProductoImagen;
    private javax.swing.JLabel ModificarProductoImagenLabel;
    private javax.swing.JButton ModificarProductoModificarButton;
    private javax.swing.JTextField ModificarProductoNombre;
    private javax.swing.JLabel ModificarProductoNombreLabel;
    private javax.swing.JSpinner ModificarProductoPrecio;
    private javax.swing.JLabel ModificarProductoPrecioLabel;
    private javax.swing.JScrollPane ModificarProductoScrollPanelDescripcion;
    private javax.swing.JScrollPane ModificarProductoScrollPanelImagen;
    private javax.swing.JScrollPane ModificarProductoScrollPanelTable;
    private javax.swing.JSpinner ModificarProductoStock;
    private javax.swing.JLabel ModificarProductoStockLabel;
    private javax.swing.JTextField ModificarProductoTipo;
    private javax.swing.JLabel ModificarProductoTipoLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
